// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TourAgency.Models;

public partial class ActualService
{
    public int Id { get; set; }

    public int ServiceId { get; set; }

    public int ClientId { get; set; }
}