// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TourAgency.Models;

public partial class Agreement
{
    public int Id { get; set; }

    public string ClientId { get; set; }

    public int Status { get; set; }

    public int Hotel { get; set; }
}