// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TourAgency.Models;

public partial class Agreement
{
    public int Id { get; set; }

    public int? ClientId { get; set; }

    public int StatusId { get; set; }

    public int HotelId { get; set; }

    public virtual ICollection<ActualService> ActualServices { get; set; } = new List<ActualService>();

    public virtual Client Client { get; set; }

    public virtual Hotel Hotel { get; set; }

    public virtual Status Status { get; set; }
}