// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TourAgency.Models;

public partial class City
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? CountryId { get; set; }

    public virtual Country Country { get; set; }

    public virtual ICollection<Tour> Tours { get; set; } = new List<Tour>();
}