// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TourAgency.Models;

public partial class ClientType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();
}