// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TourAgency.Models;

public partial class HotelsFoodType
{
    public int Id { get; set; }

    public int HotelId { get; set; }

    public int? FoodTypeId { get; set; }

    public virtual FoodType Hotel { get; set; }

    public virtual Hotel HotelNavigation { get; set; }
}