// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TourAgency.Models;

public partial class HotelsByTour
{
    public int Id { get; set; }

    public int HotelId { get; set; }

    public int TourId { get; set; }
}