// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TourAgency.Models;

public partial class ServiceType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal? Cost { get; set; }

    public virtual ICollection<ActualService> ActualServices { get; set; } = new List<ActualService>();

    public virtual ICollection<TourService> TourServices { get; set; } = new List<TourService>();
}