// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TourAgency.Models;

public partial class Tour
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal Cost { get; set; }

    public int? NeededInsuranceId { get; set; }

    public int? CityId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int? MaxPeopleCount { get; set; }

    public virtual City City { get; set; }

    public virtual ICollection<HotelsByTour> HotelsByTours { get; set; } = new List<HotelsByTour>();

    public virtual InsuranceType NeededInsurance { get; set; }

    public virtual ICollection<TourService> TourServices { get; set; } = new List<TourService>();

    public virtual ICollection<TourTypesToTour> TourTypesToTours { get; set; } = new List<TourTypesToTour>();
    public virtual ICollection<TourType> Types { get; set; } = new List<TourType>(); 
    public virtual ICollection<Hotel> Hotels { get; set; } = new List<Hotel>();
    public virtual ICollection<ServiceType> Services { get; set; } = new List<ServiceType>();
}